builds:
  - binary: php-fpm_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64

dockers:
  - image_templates:
      - "jimmybigcommerce/php-fpm_exporter:latest"
      - "jimmybigcommerce/php-fpm_exporter:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "jimmybigcommerce/php-fpm_exporter:{{ .Major }}.{{ .Minor }}"
      - "jimmybigcommerce/php-fpm_exporter:{{ .Major }}"
    build_flag_templates:
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"

archive:
  format: binary
